export const FETCH_COCKTAILS_SUCCESS = "FETCH_COCKTAILS_SUCCESS";
export const FETCH_USER_COCKTAILS_SUCCESS = "FETCH_USER_COCKTAILS_SUCCESS";
export const CREATE_COCKTAIL_SUCCESS = "CREATE_COCKTAIL_SUCCESS";

export const FETCH_FAILURE = "FETCH_FAILURE";

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';


